export const ROLE_TYPE = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  ADMIN: 'ADMIN',
  OPERATOR: 'OPERATOR',
  VIEWER: 'VIEWER',
  BILL_ADMIN: 'BILL_ADMIN',
  BILL_VIEWER: 'BILL_VIEWER',
  MIGRATOR_ADMIN: 'MIGRATOR_ADMIN',
} as const;

export const ROLE_STATE = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
} as const;
