import { i18n } from '@/app/i18n';

export const MENU_ID = Object.freeze({
  // Setting
  // Account & Access
  SETTING: 'settings',
  ACCOUNT_AND_ACCESS: 'accountAndAccess',
  ACCOUNT_AND_ACCESS_ORGANIZATIONS: 'organizations',
  ORGANIZATIONS_USERS: 'users',
  ORGANIZATIONS_APPROVALS: 'approvals',
  ORGANIZATIONS_ACCESS_CONTROLS: 'accessControls',

  // Environment
  ENVIRONMENT: 'environment',
  ENVIRONMENT_CLOUD_RESOURCES: 'cloudResources',
  // ENVIRONMENT_

  // Operations
  // Manage
  OPERATION: 'operations',
  MANAGE: 'manage',
  MANAGE_WORKLOADS: 'workloads',
  WORKLOADS_MCI: 'mci',
  WORKLOADS_PMK: 'pmk',
  MANAGE_WORKSPACE: 'workspaces',
  WORKSPACES: 'workspaces',
});

export const MENU_ID_TO_NAME = Object.freeze({
  [MENU_ID.SETTING]: i18n.t('MENU.SETTINGS._NAME'),
  [MENU_ID.ACCOUNT_AND_ACCESS]: i18n.t('MENU.SETTINGS.ACCOUNT_ACCESS._NAME'),
  [MENU_ID.ACCOUNT_AND_ACCESS_ORGANIZATIONS]: i18n.t(
    'MENU.SETTINGS.ACCOUNT_ACCESS.ORGANIZATIONS._NAME',
  ),
  [MENU_ID.ORGANIZATIONS_USERS]: i18n.t(
    'MENU.SETTINGS.ACCOUNT_ACCESS.ORGANIZATIONS.USERS',
  ),
  [MENU_ID.ORGANIZATIONS_APPROVALS]: i18n.t(
    'MENU.SETTINGS.ACCOUNT_ACCESS.ORGANIZATIONS.APPROVALS',
  ),
  [MENU_ID.ORGANIZATIONS_ACCESS_CONTROLS]: i18n.t(
    'MENU.SETTINGS.ACCOUNT_ACCESS.ORGANIZATIONS.ACCESS_CONTROLS',
  ),

  [MENU_ID.ENVIRONMENT]: i18n.t('MENU.SETTINGS.ENVIRONMENT._NAME'),
  [MENU_ID.ENVIRONMENT_CLOUD_RESOURCES]: i18n.t(
    'MENU.SETTINGS.ENVIRONMENT.CLOUD_RESOURCES._NAME',
  ),

  [MENU_ID.OPERATION]: i18n.t('MENU.OPERATIONS._NAME'),
  [MENU_ID.MANAGE]: i18n.t('MENU.OPERATIONS.MANAGE._NAME'),
  [MENU_ID.MANAGE_WORKLOADS]: i18n.t('MENU.OPERATIONS.MANAGE.WORKLOADS._NAME'),
  [MENU_ID.WORKLOADS_MCI]: i18n.t('MENU.OPERATIONS.MANAGE.WORKLOADS.MCI'),
  [MENU_ID.WORKLOADS_PMK]: i18n.t('MENU.OPERATIONS.MANAGE.WORKLOADS.PMK'),

  [MENU_ID.MANAGE_WORKSPACE]: i18n.t('WORKSPACE._NAME'),
});
