import { MENU_ID } from '@/entities';

export const ROOT_ROUTE = {
  _NAME: 'root',
  MAIN: 'main',
  ERROR: '404error',
} as const;

export const SOURCE_COMPUTING_ROUTE = {
  _NAME: MENU_ID.SOURCE_COMPUTING,
  SOURCE_SERVICES: {
    _NAME: MENU_ID.SOURCE_SERVICES,
    SOURCE_CONNECTION: {
      _NAME: MENU_ID.SOURCE_CONNECTIONS,
    },
  },
};

export const MODEL_ROUTE = {
  _NAME: MENU_ID.MODELS,
  SOURCE_MODELS: {
    _NAME: MENU_ID.SOURCE_MODELS,
  },
  TARGET_MODELS: {
    _NAME: MENU_ID.TARGET_MODELS,
  },
};

export const WORKFLOW_MANAGEMENT_ROUTE = {
  _NAME: MENU_ID.WORKFLOW_MANAGEMENT,
  WORKFLOWS: {
    _NAME: MENU_ID.WORKFLOWS,
  },
  WORKFLOW_TEMPLATES: {
    _NAME: MENU_ID.WORKFLOW_TEMPLATES,
  },
  TASK_COMPONENTS: {
    _NAME: MENU_ID.TASK_COMPONENTS,
  },
};

export const WORKLOAD_OPERATIONS_ROUTE = {
  _NAME: MENU_ID.WORKLOAD_OPERATIONS,
  WORKLOADS: {
    _NAME: MENU_ID.WORKLOADS,
    MCI_WLS: {
      _NAME: MENU_ID.MCI_WLS,
    },
    PMK_WLS: {
      _NAME: MENU_ID.PMK_WLS,
    },
  },
};
