package mcir

import (
	tbcommon "cm_butterfly/frameworkmodel/tumblebug/common"
)

type TbSecurityGroupInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`

	ConnectionName       string               `json:"connectionName"`
	CspSecurityGroupId   string               `json:"cspSecurityGroupId"`
	CspSecurityGroupName string               `json:"cspSecurityGroupName"`
	Description          string               `json:"description"`
	FirewallRules        []TbFirewallRuleInfo `json:"firewallRules"`
	ID                   string               `json:"id"`
	IsAutoGenerated      string               `json:"isAutoGenerated"`

	KeyValueList []tbcommon.TbKeyValue `json:"keyValueList"`
	Name         string                `json:"name"`
	SystemLabel  string                `json:"systemLabel"`
	VNetID       string                `json:"vNetId"`

	// connection 을 provider, regname으로 대체를 위해 추가
	ProviderID   string `json:"providerId"`
	ProviderName string `json:"providerName"`
	RegionName   string `json:"regionName"`
	ZoneName     string `json:"zoneName"`
}

type TbSecurityGroupInfos []TbSecurityGroupInfo
