package mcir

import (
	tbcommon "cm_butterfly/frameworkmodel/tumblebug/common"
)

type TbSshKeyInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`

	ConnectionName string `json:"connectionName"`
	CspSshKeyName  string `json:"cspSshKeyName"`
	CspSshKeyId    string `json:"cspSshKeyId"`
	SystemLabel    string `json:"systemLabel"`

	Description     string                `json:"description"`
	Fingerprint     string                `json:"fingerprint"`
	ID              string                `json:"id"`
	IsAutoGenerated bool                  `json:"isAutoGenerated"`
	KeyValueInfos   []tbcommon.TbKeyValue `json:"keyValueList"`

	Name             string `json:"name"`
	PrivateKey       string `json:"privateKey"`
	PublicKey        string `json:"publicKey"`
	Username         string `json:"username"`
	VerifiedUsername string `json:"verifiedUsername"`

	ProviderID   string `json:"providerId"`
	ProviderName string `json:"providerName"`
	RegionName   string `json:"regionName"`
	ZoneName     string `json:"zoneName"`
}

type TbSshKeyInfos []TbSshKeyInfo
