package mcir

import (
	tbcommon "cm_butterfly/frameworkmodel/tumblebug/common"
)

type TbVNetInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`

	CidrBlock      string `json:"cidrBlock"`
	ConnectionName string `json:"connectionName"`
	CspVNetID      string `json:"cspVNetId"`
	CspVNetName    string `json:"cspVNetName"`

	Description     string                `json:"description"`
	ID              string                `json:"id"`
	IsAutoGenerated bool                  `json:"isAutoGenerated"`
	KeyValueInfos   []tbcommon.TbKeyValue `json:"keyValueList"`

	Name           string         `json:"name"`
	Statue         string         `json:"status"`
	SubnetInfoList []TbSubnetInfo `json:"subnetInfoList"`
	SystemLabel    string         `json:"systemLabel"`

	// connection 을 provider, regname으로 대체를 위해 추가
	ProviderID   string `json:"providerId"`
	ProviderName string `json:"providerName"`
	RegionName   string `json:"regionName"`
	ZoneName     string `json:"zoneName"`
}

type TbVNetInfos []TbVNetInfo
